### PR TITLE
Fix eks-anywhere formula on arm

### LINKED ISSUE #228: Unable to add tap - Invalid formula: /opt/homebrew/Library/Taps/aws/homebrew-tap/Formula/eks-anywhere.rb
OS X Big Sur 11.5.2
Apple M1

➜ brew --version
Homebrew 3.2.11
Homebrew/homebrew-core (git revision 4f77196f8a; last commit 2021-09-09)
Homebrew/homebrew-cask (git revision 7edff39a8e; last commit 2021-09-09)

➜ brew tap aws/tap
==> Tapping aws/tap
Cloning into '/opt/homebrew/Library/Taps/aws/homebrew-tap'...
remote: Enumerating objects: 2222, done.
remote: Counting objects: 100% (985/985), done.
remote: Compressing objects: 100% (631/631), done.
remote: Total 2222 (delta 817), reused 450 (delta 353), pack-reused 1237
Receiving objects: 100% (2222/2222), 355.74 KiB | 110.00 KiB/s, done.
Resolving deltas: 100% (1478/1478), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/aws/homebrew-tap/Formula/eks-anywhere.rb
formulae require at least a URL
Error: Cannot tap aws/tap: invalid syntax in tap!

### PR DESCRIPTION
**Pull request by eddiezane**
*Issue #, if available:*

Fixes #228

*Description of changes:*

This PR fixes an issue with the eks-anywhere formula under ARM CPU's while we figure out a proper fix. This will install the amd64 version but warn the user that it will not work and the the formula should be uninstalled.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: Formula/eks-anywhere.rb [hunk 1]
```diff
@@ -1,26 +1,33 @@
...
+  if OS.linux?
+    url "https://anywhere-assets.eks.amazonaws.com/releases/eks-a/1/artifacts/eks-a/v0.5.0/linux/eksctl-anywhere-v0.5.0-linux-amd64.tar.gz"
+    sha256 "020ae9fb3b01070bda29e530d157089bf56e11245bde098118ea0350ed5f5ec4"
+  end
+
+  # if Hardware::CPU.arm?
+    def caveats
+      <<~EOF
+          =====WARNING=====
+          ARM CPU's are not yet supported.
```
Comment (bwagner5) [inline Formula/eks-anywhere.rb:21]: I don't think the warning is necessary. The amd64 version should work on an arm64 (m1) mac currently with Rosetta 2 completely transparently.

**Review by bwagner5 — APPROVED** [review]
lgtm

File: Formula/eks-anywhere.rb (hunk 1 above)
Comment (bwagner5) [reply Formula/eks-anywhere.rb:21]: ah doesn't work because kind doesn't publish arm64 docker images 👍
